server:
  port: 8089

spring:
  thymeleaf:
    cache: false
    checkTemplateLocation: true
    prefix:file: src/main/resources/templates/
    suffix: .html

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddlAuto: create
      showSql: true
      formatSql: true
    openInView: false

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG